title: 福岡県BBS連盟HP
description: BBSとは"Big Brothers and Sisters"の略称です。少年（少女）が、良き兄や姉のような存在として、同じ世代の悩みを持ち、時には犯罪や非行に陥ってしまった少年少女たちを支援する活動です。私たちは、様々な事情で困難を抱える若者たちに寄り添い、共に未来を考える「ともだち活動」をしています。
layout: default
lang: ja
url: "https://fukuokaprefbbs.github.io"

# Jekyll設定
markdown: kramdown
highlighter: rouge
permalink: pretty

# Kramdown設定
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# プラグイ
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets

# アセット管理設定
assets:
  compress:
    css: true
    js: true
  cachebust: hard
  gzip: false
  digest: true
  prefix: "/assets"
  sources:
    - _assets/css
    - _assets/js
    - _assets/images

# 除外ファイル・ディレクトリ
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - README.md
  - vendor
  - node_modules
  - .bundle
  - .jekyll-cache
  - _site

# インクルードファイル・ディレクトリ
include:
  - _pages
  - _posts

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
