# Jekyll基本設定
title: "福岡県BBS連盟"
description: "BBSとは'Big Brothers and Sisters'の略称です。少年（少女）が、良き兄や姉のような存在として、同じ世代の悩みを持ち、時には犯罪や非行に陥ってしまった少年少女たちを支援する活動です。"
tagline: "あたたかい心で、ともだち活動を。"
url: "https://fukuokaprefbbs.github.io"
baseurl: ""
lang: ja
timezone: Asia/Tokyo

markdown: kramdown
highlighter: rouge
permalink: pretty

# Kramdown設定
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 除外ファイル・ディレクトリ
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - README.md
  - vendor
  - node_modules
  - .bundle
  - .jekyll-cache
  - _site

# インクルードファイル・ディレクトリ
include:
  - _pages
  - _posts

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  
  - scope:
      path: "_pages"
    values:
      permalink: "/:basename/"
