title: 福岡県BBS連盟HP
description: BBSとは"Big Brothers and Sisters"の略称です。少年（少女）が、良き兄や姉のような存在として、同じ世代の悩みを持ち、時には犯罪や非行に陥ってしまった少年少女たちを支援する活動です。私たちは、様々な事情で困難を抱える若者たちに寄り添い、共に未来を考える「ともだち活動」をしています。
layout: default
lang: ja
url: "https://fukuokaprefbbs.github.io"

# Jekyll設定
markdown: kramdown
highlighter: rouge
permalink: pretty

# プラグイン（必要最小限）
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 除外ファイル
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - README.md

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
