layout: default
lang: ja
url: "https://fukuokaprefbbs.github.io"
baseurl: ""

# Jekyll設定
markdown: kramdown
highlighter: rouge
permalink: pretty

# Kramdown設定
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 除外ファイル・ディレクトリ
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .github
  - README.md
  - vendor
  - node_modules
  - .bundle
  - .jekyll-cache
  - _site

# インクルードファイル・ディレクトリ
include:
  - _pages
  - _posts

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"

# キャッシュバスティング設定
timezone: Asia/Tokyo
