title: "福岡県BBS連盟"
description: "BBSとは'Big Brothers and Sisters'の略称です。少年（少女）が、良き兄や姉のような存在として、同じ世代の悩みを持ち、時には犯罪や非行に陥ってしまった少年少女たちを支援する活動です。"
tagline: "あたたかい心で、ともだち活動を。"
url: "https://fukuokaprefbbs.github.io"
email: "fukuokaprefbbs@gmail.com"
phone: "0927616736"

# 組織情報
organization:
  name: "福岡県BBS連盟"
  type: "県連盟"
  description: "福岡県内のBBS活動を統括する組織"
  
# ソーシャルメディア（県連盟公式）
social:
  twitter:
    url: ""
    username: ""
  facebook:
    url: ""
    username: ""
  instagram:
    url: ""
    username: ""

# 所在地
address:
  organization: "福岡県ＢＢＳ連盟"
  postal_code: "810-0044"
  prefecture: "福岡県"
  city: "福岡市中央区"
  street: "六本松4-2-3"
  building: "福岡法務総合庁舎1F 福岡保護観察所内"

# 活動内容
activities:
  - title: "ともだち活動"
    description: "少年少女と兄や姉のような立場で接し、共に悩み、考え、支え合う活動です。"
    icon: "bi-people-fill"
    color: "primary"
  
  - title: "広報・啓発活動"
    description: "地域社会へBBS活動の重要性を伝え、理解を深めてもらうための活動です。"
    icon: "bi-handshake-fill"
    color: "success"
  
  - title: "研修・学習活動"
    description: "活動に必要な知識やスキルを習得し、会員同士の交流を深めます。"
    icon: "bi-book-fill"
    color: "info"

# 地区会（県内の各地域組織）
regional_groups:
  - name: "福岡市BBS会"
    description: "福岡市エリアのBBS活動"
    url: "https://twitter.com/Fukuokacitybbs"
    platform: "Twitter"
    icon: "bi-twitter"
    note: "福岡市エリアの地区会"
  
  - name: "九州大学BBS会"
    description: "九州大学内のBBS活動"
    url: "https://twitter.com/BBS_qdai"
    platform: "Twitter"
    icon: "bi-twitter"
    note: "九州大学内の学生組織"
  
  - name: "九州国際大学BBS会"
    description: "九州国際大学内のBBS活動"
    url: "https://twitter.com/kmatsumoto01"
    platform: "Twitter"
    icon: "bi-twitter"
    note: "九州国際大学内の学生組織"

# 組織構造の説明
structure_note: |
  福岡県BBS連盟は、福岡県内の各地域・大学のBBS会を統括する組織です。
  各地域・大学のBBS会は独立した活動を行いながら、県連盟を通じて連携しています。

# メタ情報
meta:
  keywords: "BBS, 福岡県, 若者支援, ともだち活動, 少年少女支援, 非行防止, 福岡県BBS連盟"
  author: "福岡県BBS連盟"
  robots: "index, follow"
  og_type: "website"
  twitter_card: "summary_large_image"
